version: "3.7"

services:
  movie-service:
    image: tenshyy/movie-service:latest  
    deploy:
      replicas: 2
    ports:
      - "5001:5001"
    networks:
      - cinema-net

  ticket-service:
    image: tenshyy/ticket-service:latest  
    deploy:
      replicas: 2
    ports:
      - "5002:5002"
    networks:
      - cinema-net
    depends_on:
      - movie-service

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 1
    depends_on:
      - movie-service
      - ticket-service
    networks:
      - cinema-net

networks:
  cinema-net:
    driver: overlay