version: "3.9"

services:
  movie-service:
    build: ./movie-service
    ports:
      - "5001:5001"
    networks:
      - cinema-net

  ticket-service:
    build: ./ticket-service
    ports:
      - "5002:5002"
    networks:
      - cinema-net
    depends_on:
      - movie-service

networks:
  cinema-net:
    driver: bridge